In [4]:
from gutenberg.acquire import load_etext
from gutenberg.cleanup import strip_headers
import nltk

In [39]:
import seaborn as sns
import numpy as np
def get_length_kde(book_id):
    book = load_etext(book_id)
    book = strip_headers(book)
    sents = [nltk.word_tokenize(str.lower(s)) for s in nltk.sent_tokenize(book)]
    
    lengths = [len(s) for s in sents]
    print(np.quantile(lengths, [0.25, 0.75]))
    sns.kdeplot(data=lengths)
    
def get_sentence_lengths(book_id):
    book = load_etext(book_id)
    book = strip_headers(book)
    return [len(nltk.word_tokenize(str.lower(s))) for s in nltk.sent_tokenize(book)]


In [67]:
from collections import Counter
from functools import reduce
import operator
from scipy.spatial import distance
from gutenberg.acquire import load_etext
from gutenberg.cleanup import strip_headers

def load_and_strip(book_id):
    return strip_headers(load_etext(book_id))

def get_probability_vec(lengths, max_sent_length):
    result = np.zeros(max_sent_length + 1)
    for i, count in Counter(lengths).items():
        result[i] = count
        
    return result / result.sum()

def get_sentence_lengths_num_words(text):
    [len(nltk.word_tokenize(s)) for s in nltk.sent_tokenize(text)]

def sentence_length_question(q):
    books = [load_and_strip(id) for id in q["answers"]]
    
    book_sent_lengths = [get_sentence_lengths_num_words(text) for id in books]
    # get max sentence length
    max_sent_length = max([l for sent_lengths in book_sent_lengths
        for l in sent_lengths])

    probability_vecs = [get_probability_vec(lengths, max_sent_length)
     for lengths in book_sent_lengths]

    avg_probability_vec = reduce(operator.add, probability_vecs) / len(probability_vecs)

    _, index_of_most_different = max([
        (distance.jensenshannon(v, avg_probability_vec), i)
        for i, v in enumerate(probability_vecs)
    ])

# fill zeros to max length where index is the sentence length
# get probabilities where index is the 
# combinations of N-1 vs left out
# see who is the most different from the average
# return answer + probability distribution for sentence lengths for average vs other 


In [71]:
[a, b] = {"a":1, "b":4, "c":6}

ValueError: too many values to unpack (expected 2)

In [54]:
[(k,v) for k, v in Counter([1, 1, 2, 3]).items()]

[(1, 2), (2, 1), (3, 1)]

In [108]:
from collections import Counter
c = Counter([1,2,3,1,2])

In [112]:
c.most_common(2)

[(1, 2), (2, 2)]

In [104]:
from nltk import FreqDist

# JJ	adjective	'big'
# JJR	adjective, comparative	'bigger'
# JJS	adjective, superlative	'biggest'

adjectives = [x[0] for x in filtered_tagged_words if x[1] in {"JJ", "JJR", "JJS"}]
freq_dist = FreqDist(adjectives)

In [149]:
np.array([np.array([1,2]), np.array([5,5])]).sum(axis=1).argmax(axis=)

AxisError: axis 1 is out of bounds for array of dimension 1

In [156]:
arr = np.array([np.array([1,2]), np.array([5,5])])

In [165]:
print(np.array([np.array(l) for l in [[1,2,3], [2,3,4]]]))

[[1 2 3]
 [2 3 4]]


In [72]:
from sklearn.neighbors import KernelDensity
import numpy as np

In [73]:
X = np.array([1, 1, 2, 2, 3, 3, 4, 5, 6, 8, 10])
kde = KernelDensity(kernel='gaussian', bandwidth=0.2).fit(X)
kde.score_samples(X)

ValueError: Expected 2D array, got 1D array instead:
array=[ 1.  1.  2.  2.  3.  3.  4.  5.  6.  8. 10.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [74]:
def make_data(N, f=0.3, rseed=1):
    rand = np.random.RandomState(rseed)
    x = rand.randn(N)
    x[int(f * N):] += 5
    return x

x = make_data(1000)


In [97]:
x

array([ 1.62434536e+00, -6.11756414e-01, -5.28171752e-01, -1.07296862e+00,
        8.65407629e-01, -2.30153870e+00,  1.74481176e+00, -7.61206901e-01,
        3.19039096e-01, -2.49370375e-01,  1.46210794e+00, -2.06014071e+00,
       -3.22417204e-01, -3.84054355e-01,  1.13376944e+00, -1.09989127e+00,
       -1.72428208e-01, -8.77858418e-01,  4.22137467e-02,  5.82815214e-01,
       -1.10061918e+00,  1.14472371e+00,  9.01590721e-01,  5.02494339e-01,
        9.00855949e-01, -6.83727859e-01, -1.22890226e-01, -9.35769434e-01,
       -2.67888080e-01,  5.30355467e-01, -6.91660752e-01, -3.96753527e-01,
       -6.87172700e-01, -8.45205641e-01, -6.71246131e-01, -1.26645989e-02,
       -1.11731035e+00,  2.34415698e-01,  1.65980218e+00,  7.42044161e-01,
       -1.91835552e-01, -8.87628964e-01, -7.47158294e-01,  1.69245460e+00,
        5.08077548e-02, -6.36995647e-01,  1.90915485e-01,  2.10025514e+00,
        1.20158952e-01,  6.17203110e-01,  3.00170320e-01, -3.52249846e-01,
       -1.14251820e+00, -

In [77]:
kde = KernelDensity(bandwidth=1.0, kernel='gaussian')
kde.fit(x[:, None])

KernelDensity()

In [98]:
X_plot = np.linspace(-6, 6, 1000)[:, None]

In [100]:
X_plot

array([[-6.        ],
       [-5.98798799],
       [-5.97597598],
       [-5.96396396],
       [-5.95195195],
       [-5.93993994],
       [-5.92792793],
       [-5.91591592],
       [-5.9039039 ],
       [-5.89189189],
       [-5.87987988],
       [-5.86786787],
       [-5.85585586],
       [-5.84384384],
       [-5.83183183],
       [-5.81981982],
       [-5.80780781],
       [-5.7957958 ],
       [-5.78378378],
       [-5.77177177],
       [-5.75975976],
       [-5.74774775],
       [-5.73573574],
       [-5.72372372],
       [-5.71171171],
       [-5.6996997 ],
       [-5.68768769],
       [-5.67567568],
       [-5.66366366],
       [-5.65165165],
       [-5.63963964],
       [-5.62762763],
       [-5.61561562],
       [-5.6036036 ],
       [-5.59159159],
       [-5.57957958],
       [-5.56756757],
       [-5.55555556],
       [-5.54354354],
       [-5.53153153],
       [-5.51951952],
       [-5.50750751],
       [-5.4954955 ],
       [-5.48348348],
       [-5.47147147],
       [-5

In [93]:
np.array([1,2,3]).reshape(3,1).shape

(3, 1)